# Generated by Django 5.2.17 on 2026-09-22 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        ('referentiels', '0002_currency_unitofmeasure_account_analyticaxis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StocksSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10, unique=True, verbose_name='Type')),
                ('prefix', models.CharField(max_length=10, verbose_name='Préfixe')),
                ('padding', models.PositiveSmallIntegerField(default=5, verbose_name='Zéro-padding')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Prochain numéro')),
            ],
            options={
                'verbose_name': 'Séquence Stocks',
                'verbose_name_plural': 'Séquences Stocks',
            },
        ),
        migrations.CreateModel(
            name='ArticleStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode', models.CharField(choices=[('fifo', 'FIFO / PEPS'), ('peps', 'PEPS'), ('cump', 'CUMP (coût moyen pondéré)'), ('pp', 'Prix préétabli / standard')], default='cump', max_length=8, verbose_name='Méthode de valorisation')),
                ('prix_standard', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Prix préétabli (standard)')),
                ('seuil_minimal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Seuil minimum de stock')),
                ('gestion_lots', models.BooleanField(default=False, verbose_name='Gestion par lots')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_config', to='referentiels.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Paramétrage stock article',
                'verbose_name_plural': 'Paramétrages stock articles',
                'ordering': ['article__code'],
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=200, verbose_name='Désignation')),
                ('site', models.CharField(blank=True, max_length=120, verbose_name='Site / localisation')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks_depots', to=settings.AUTH_USER_MODEL, verbose_name='Responsable magasin')),
            ],
            options={
                'verbose_name': 'Dépôt / magasin',
                'verbose_name_plural': 'Dépôts / magasins',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('date', models.DateField(verbose_name="Date d'inventaire")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', 'En cours'), ('cloture', 'Clôturé'), ('annule', 'Annulé')], default='brouillon', max_length=12, verbose_name='Statut')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks_inventaires_cree', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventaires', to='stocks.depot', verbose_name='Dépôt')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks_inventaires', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LotMatiere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('numero_lot', models.CharField(max_length=80, verbose_name='N° lot fournisseur')),
                ('date_reception', models.DateField(verbose_name='Date de réception')),
                ('date_peremption', models.DateField(blank=True, null=True, verbose_name='Date de péremption')),
                ('quantite_initiale', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Quantité initiale')),
                ('quantite_restante', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Quantité restante')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('partiel', 'Partiellement consommé'), ('epuise', 'Épuisé'), ('bloque', 'Bloqué')], default='disponible', max_length=12, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='referentiels.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Lot de matière',
                'verbose_name_plural': 'Lots de matière',
                'ordering': ['-date_reception', 'code'],
            },
        ),
        migrations.CreateModel(
            name='InventaireLigne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite_systeme', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Quantité système')),
                ('quantite_reelle', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Quantité réelle')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaire_lignes', to='referentiels.article', verbose_name='Article')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stocks.inventaire', verbose_name='Inventaire')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaire_lignes', to='stocks.lotmatiere', verbose_name='Lot')),
            ],
            options={
                'verbose_name': "Ligne d'inventaire",
                'verbose_name_plural': "Lignes d'inventaire",
                'ordering': ['inventaire', 'article__code'],
            },
        ),
        migrations.CreateModel(
            name='CertificatMatiere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('type', models.CharField(choices=[('mtc', 'MTC (Mill Test Certificate)'), ('coc', 'CoC (Certificate of Conformity)')], default='mtc', max_length=4, verbose_name='Type')),
                ('numero_certificat', models.CharField(max_length=80, verbose_name='N° certificat')),
                ('organisme', models.CharField(blank=True, max_length=120, verbose_name='Organisme / labo')),
                ('date_emission', models.DateField(blank=True, null=True, verbose_name="Date d'émission")),
                ('date_validation', models.DateField(blank=True, null=True, verbose_name='Date de validation QA-QC')),
                ('conforme', models.BooleanField(default=True, verbose_name='Conforme')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificats_matiere', to='referentiels.partner', verbose_name='Fournisseur')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='stocks.lotmatiere', verbose_name='Lot')),
            ],
            options={
                'verbose_name': 'Certificat matière',
                'verbose_name_plural': 'Certificats matière',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('type_mouvement', models.CharField(choices=[('reception', 'Réception'), ('transfert', 'Transfert entre dépôts'), ('consommation', 'Consommation (OF / chantier)'), ('retour', 'Retour'), ('inventaire', "Ajustement d'inventaire")], default='reception', max_length=12, verbose_name='Type')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Prix unitaire')),
                ('document_reference', models.CharField(blank=True, max_length=60, verbose_name='Réf. document (BC / BL / INV)')),
                ('date', models.DateField(verbose_name='Date du mouvement')),
                ('executed', models.BooleanField(default=False, verbose_name='Appliqué aux quants')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock', to='referentiels.article', verbose_name='Article')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks_mouvements', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_entrants', to='stocks.depot', verbose_name='Dépôt destination')),
                ('devise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to='referentiels.currency', verbose_name='Devise')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='stocks.lotmatiere', verbose_name='Lot')),
                ('ordre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='operations.ordrefabrication', verbose_name='Ordre de fabrication')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_sortants', to='stocks.depot', verbose_name='Dépôt source')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockQuant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Quantité en stock')),
                ('stock_value', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Valeur du stock')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quants', to='referentiels.article', verbose_name='Article')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quants', to='stocks.depot', verbose_name='Dépôt')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quants', to='stocks.lotmatiere', verbose_name='Lot')),
            ],
            options={
                'verbose_name': 'Quant en stock',
                'verbose_name_plural': 'Quants en stock',
                'ordering': ['depot', 'article__code'],
            },
        ),
        migrations.AddIndex(
            model_name='inventaire',
            index=models.Index(fields=['depot', 'statut'], name='stocks_inve_depot_i_72eae7_idx'),
        ),
        migrations.AddIndex(
            model_name='lotmatiere',
            index=models.Index(fields=['article', 'statut'], name='stocks_lotm_article_3080ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='certificatmatiere',
            unique_together={('lot', 'numero_certificat')},
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['article', 'type_mouvement'], name='stocks_mouv_article_7cd048_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockquant',
            constraint=models.UniqueConstraint(condition=models.Q(('lot__isnull', True)), fields=('depot', 'article'), name='quant_sans_lot_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stockquant',
            constraint=models.UniqueConstraint(condition=models.Q(('lot__isnull', False)), fields=('depot', 'article', 'lot'), name='quant_lot_uniq'),
        ),
    ]
