# Generated by Django 5.2.17 on 2026-09-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annexe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('kind', models.CharField(choices=[('F', 'Formulaire'), ('R', 'Registre'), ('M', 'Modèle'), ('TS', 'Tableau de suivi')], db_index=True, max_length=2, verbose_name='Nature')),
                ('domain', models.CharField(choices=[('ADM', 'Administratif'), ('FIN', 'Finance'), ('TEC', 'Technique'), ('COM', 'Commercial'), ('RH', 'Ressources humaines'), ('JUR', 'Juridique'), ('HSE', 'HSE')], db_index=True, max_length=3, verbose_name='Domaine')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('source_ref', models.CharField(blank=True, help_text='Ex. chapitre / §10.4 (les intitulés précis seront complétés par le client).', max_length=120, verbose_name='Référence MANUEL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Annexe',
                'verbose_name_plural': 'Annexes',
                'ordering': ['domain', 'kind', 'code'],
                'indexes': [models.Index(fields=['domain', 'kind'], name='referentiel_domain_247fbb_idx')],
            },
        ),
    ]
