# Generated by Django 5.2.17 on 2026-09-21 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Code ISO')),
                ('label', models.CharField(max_length=60, verbose_name='Libellé')),
                ('symbol', models.CharField(blank=True, max_length=8, verbose_name='Symbole')),
                ('decimals', models.PositiveSmallIntegerField(default=0, verbose_name='Décimales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Devise',
                'verbose_name_plural': 'Devises',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=60, verbose_name='Libellé')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Unité de mesure',
                'verbose_name_plural': 'Unités de mesure',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Numéro de compte')),
                ('label', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('account_class', models.PositiveSmallIntegerField(choices=[(1, 'Comptes de ressources durables'), (2, "Comptes d'actif immobilisé"), (3, 'Comptes de stocks'), (4, 'Comptes de tiers'), (5, 'Comptes de trésorerie'), (6, 'Comptes de charges'), (7, 'Comptes de produits'), (8, 'Comptes des autres charges et autres produits')], db_index=True, verbose_name='Classe')),
                ('account_type', models.CharField(choices=[('asset', 'Actif'), ('liability', 'Passif'), ('equity', 'Capitaux propres'), ('income', 'Produit'), ('expense', 'Charge')], max_length=10, verbose_name='Nature')),
                ('reconcile', models.BooleanField(default=False, help_text='Rapprochement / lettrage.', verbose_name='Lettrable')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='referentiels.account', verbose_name='Compte parent')),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Comptes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticAxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=120, verbose_name='Libellé')),
                ('axis_type', models.CharField(choices=[('projet', 'Projet / affaire'), ('chantier', 'Chantier'), ('centre_cout', 'Centre de coût'), ('site', 'Site')], db_index=True, max_length=12, verbose_name="Type d'axe")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='referentiels.analyticaxis', verbose_name='Axe parent')),
            ],
            options={
                'verbose_name': 'Axe analytique',
                'verbose_name_plural': 'Axes analytiques',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='Code')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='referentiels.analyticaxis', verbose_name='Axe')),
            ],
            options={
                'verbose_name': 'Valeur analytique',
                'verbose_name_plural': 'Valeurs analytiques',
                'ordering': ['axis', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Raison sociale')),
                ('kind', models.CharField(choices=[('client', 'Client'), ('fournisseur', 'Fournisseur'), ('both', 'Client et fournisseur'), ('autre', 'Autre')], db_index=True, max_length=12, verbose_name='Type')),
                ('tax_id', models.CharField(blank=True, max_length=40, verbose_name='NIF / identifiant fiscal')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('is_global_rental', models.BooleanField(default=False, verbose_name='Intra-groupe GLOBAL RENTAL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='referentiels.currency', verbose_name='Devise')),
            ],
            options={
                'verbose_name': 'Tiers',
                'verbose_name_plural': 'Tiers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=200, verbose_name='Désignation')),
                ('article_type', models.CharField(choices=[('produit', 'Produit'), ('service', 'Service / prestation'), ('matiere', 'Matière première'), ('consommable', 'Consommable')], db_index=True, max_length=12, verbose_name='Type')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="Prix d'achat")),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Prix de vente')),
                ('is_stockable', models.BooleanField(default=False, verbose_name='Géré en stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='referentiels.account', verbose_name='Compte de rattachement')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='referentiels.unitofmeasure', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['code'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_class', 'account_type'], name='referentiel_account_eed50c_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticaccount',
            constraint=models.UniqueConstraint(fields=('axis', 'code'), name='uniq_analytic_value'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['kind', 'is_active'], name='referentiel_kind_a132b7_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['article_type', 'is_active'], name='referentiel_article_d46dcb_idx'),
        ),
    ]
