# Generated by Django 5.2.17 on 2026-09-21 18:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiels', '0002_currency_unitofmeasure_account_analyticaxis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchatsSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10, unique=True, verbose_name='Type')),
                ('prefix', models.CharField(max_length=10, verbose_name='Préfixe')),
                ('padding', models.PositiveSmallIntegerField(default=5, verbose_name='Zéro-padding')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Prochain numéro')),
            ],
            options={
                'verbose_name': 'Séquence Achats',
                'verbose_name_plural': 'Séquences Achats',
            },
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('subject', models.CharField(max_length=200, verbose_name='Objet')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date limite d'offre")),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('ouverte', 'Ouverte'), ('cloturee', 'Clôturée')], default='brouillon', max_length=12, verbose_name='Statut')),
                ('items', models.JSONField(blank=True, default=list, verbose_name='Lignes consultées')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consultation fournisseurs',
                'verbose_name_plural': 'Consultations fournisseurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant')),
                ('delivery_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Délai (jours)')),
                ('is_selected', models.BooleanField(default=False, verbose_name='Retenue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_offers', to='referentiels.partner', verbose_name='Fournisseur')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='achats.consultationrequest', verbose_name='Consultation')),
            ],
            options={
                'verbose_name': 'Offre de consultation',
                'verbose_name_plural': 'Offres de consultation',
                'ordering': ['consultation', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('order_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Livraison attendue')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('confirmee', 'Confirmée'), ('partielle', 'Réception partielle'), ('cloturee', 'Clôturée (réception totale)'), ('annulee', 'Annulée')], default='brouillon', max_length=12, verbose_name='Statut')),
                ('is_global_rental', models.BooleanField(default=False, verbose_name='Intra-groupe GLOBAL RENTAL')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='achats.consultationrequest', verbose_name='Consultation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiels.currency', verbose_name='Devise')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='referentiels.partner', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Bon de commande',
                'verbose_name_plural': 'Bons de commande',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('invoice_ref', models.CharField(blank=True, default='', max_length=100, verbose_name='Réf. fournisseur')),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de facture')),
                ('status', models.CharField(choices=[('en_attente', 'En attente de rapprochement'), ('rapprochee', 'Rapprochée'), ('annulee', 'Annulée')], default='en_attente', max_length=12, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiels.currency', verbose_name='Devise')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices', to='referentiels.partner', verbose_name='Fournisseur')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='achats.purchaseorder', verbose_name='Bon de commande')),
            ],
            options={
                'verbose_name': 'Facture fournisseur',
                'verbose_name_plural': 'Factures fournisseurs',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('received_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de réception')),
                ('status', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('annule', 'Annulé')], default='en_attente', max_length=12, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Réceptionné par')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='achats.purchaseorder', verbose_name='Bon de commande')),
            ],
            options={
                'verbose_name': 'Bon de livraison / réception',
                'verbose_name_plural': 'Bons de livraison / réceptions',
                'ordering': ['-received_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200, verbose_name='Désignation')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=14, verbose_name='Qté')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Prix unitaire')),
                ('price_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total ligne')),
                ('received_qty', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Qté reçue')),
                ('invoiced_qty', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Qté facturée')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_lines', to='referentiels.article', verbose_name='Article')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='achats.purchaseorder', verbose_name='Bon de commande')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiels.unitofmeasure', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Ligne de bon de commande',
                'verbose_name_plural': 'Lignes de bon de commande',
                'ordering': ['purchase_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Qté facturée')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Prix unitaire')),
                ('price_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total ligne')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='achats.purchaseinvoice', verbose_name='Facture')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='achats.purchaseorderline', verbose_name='Ligne BC')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
                'ordering': ['invoice', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Qté reçue')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='Commentaire')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='achats.goodsreceipt', verbose_name='Réception')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_lines', to='achats.purchaseorderline', verbose_name='Ligne BC')),
            ],
            options={
                'verbose_name': 'Ligne de réception',
                'verbose_name_plural': 'Lignes de réception',
                'ordering': ['receipt', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('title', models.CharField(max_length=200, verbose_name='Objet')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Service')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Échéance souhaitée')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée'), ('convertie', 'Convertie en commande')], default='brouillon', max_length=14, verbose_name='Statut')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Urgente')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
            ],
            options={
                'verbose_name': "Demande d'achat",
                'verbose_name_plural': "Demandes d'achat",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='achats.purchaserequest', verbose_name="Demande d'achat"),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='achats.purchaserequest', verbose_name="Demande d'achat"),
        ),
        migrations.CreateModel(
            name='PurchaseRequestLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200, verbose_name='Désignation')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=14, verbose_name='Qté')),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Prix estimé unitaire')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request_lines', to='referentiels.article', verbose_name='Article')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='achats.purchaserequest', verbose_name='Demande')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiels.unitofmeasure', verbose_name='Unité')),
            ],
            options={
                'verbose_name': "Ligne de demande d'achat",
                'verbose_name_plural': "Lignes de demande d'achat",
                'ordering': ['request', 'id'],
            },
        ),
    ]
