# Generated by Django 5.2.17 on 2026-09-22 01:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0001_initial'),
        ('referentiels', '0002_currency_unitofmeasure_account_analyticaxis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GammeOperatoire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('active', 'Active'), ('archivee', 'Archivée')], default='brouillon', max_length=12, verbose_name='Statut')),
                ('is_global_rental', models.BooleanField(default=False, verbose_name='GLOBAL RENTAL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gamme opératoire',
                'verbose_name_plural': 'Gammes opératoires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationsSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10, unique=True, verbose_name='Type')),
                ('prefix', models.CharField(max_length=10, verbose_name='Préfixe')),
                ('padding', models.PositiveSmallIntegerField(default=5, verbose_name='Zéro-padding')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Prochain numéro')),
            ],
            options={
                'verbose_name': 'Séquence Opérations',
                'verbose_name_plural': 'Séquences Opérations',
            },
        ),
        migrations.CreateModel(
            name='OrdreFabrication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=200, verbose_name='Désignation')),
                ('scope', models.CharField(choices=[('atelier', 'Atelier'), ('chantier', 'Chantier')], default='atelier', max_length=10, verbose_name='Périmètre')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=14, verbose_name='Quantité')),
                ('status', models.CharField(choices=[('prevu', 'Prévu'), ('lance', 'Lancé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('cloture', 'Clôturé'), ('annule', 'Annulé')], default='prevu', max_length=10, verbose_name='Statut')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='Début prévu')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='Fin prévue')),
                ('calculated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Heures calculées (gamme)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_fabrication', to='commercial.affaire', verbose_name='Affaire')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiels.article', verbose_name='Ouvrage / article')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_created_ordres', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('gamme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_fabrication', to='operations.gammeoperatoire', verbose_name='Gamme type')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_ordres', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Ordre de fabrication',
                'verbose_name_plural': 'Ordres de fabrication',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointageChantier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('worker_name', models.CharField(blank=True, max_length=150, verbose_name='Nom opérateur')),
                ('date', models.DateField(verbose_name='Date')),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Heures')),
                ('hours_type', models.CharField(choices=[('normal', 'Heures normales'), ('supplementaire', 'Heures supplémentaires'), ('nuit', 'Heures de nuit'), ('astreinte', 'Astreinte')], default='normal', max_length=14, verbose_name="Type d'heures")),
                ('status', models.CharField(choices=[('saisi', 'Saisi'), ('valide', 'Validé'), ('transfere', 'Transféré paie (M9)')], default='saisi', max_length=12, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_created_pointages', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
                ('ordre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='operations.ordrefabrication', verbose_name='Ordre de fabrication')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_pointages', to=settings.AUTH_USER_MODEL, verbose_name='Opérateur')),
            ],
            options={
                'verbose_name': "Pointage main-d'œuvre",
                'verbose_name_plural': "Pointages main-d'œuvre",
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SituationTravaux',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('period_start', models.DateField(verbose_name='Début période')),
                ('period_end', models.DateField(verbose_name='Fin période')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Avancement (%)')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('validee', 'Validée'), ('facturee', 'Facturée')], default='brouillon', max_length=12, verbose_name='Statut')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='situations_travaux', to='commercial.affaire', verbose_name='Affaire')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_created_situations', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('ordres', models.ManyToManyField(blank=True, related_name='situations', to='operations.ordrefabrication', verbose_name='Ordres de fabrication rattachés')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_validated_situations', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Situation de travaux',
                'verbose_name_plural': 'Situations de travaux',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GammeOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('label', models.CharField(max_length=200, verbose_name='Opération')),
                ('poste', models.CharField(choices=[('decoupe', 'Découpe'), ('tuyauterie', 'Tuyauterie'), ('soudure', 'Soudure'), ('chaudronnerie', 'Chaudronnerie'), ('structure', 'Structures métalliques'), ('montage', 'Montage'), ('controle', 'Contrôle / essais')], default='tuyauterie', max_length=16, verbose_name='Poste')),
                ('planned_hours', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Heures prévues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gamme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='operations.gammeoperatoire', verbose_name='Gamme')),
            ],
            options={
                'verbose_name': 'Opération de gamme',
                'verbose_name_plural': 'Opérations de gamme',
                'ordering': ['gamme', 'sequence'],
                'indexes': [models.Index(fields=['gamme', 'sequence'], name='operations__gamme_i_4ad559_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ordrefabrication',
            index=models.Index(fields=['status', 'scope'], name='operations__status_1ced62_idx'),
        ),
        migrations.AddIndex(
            model_name='pointagechantier',
            index=models.Index(fields=['date', 'status'], name='operations__date_2f8329_idx'),
        ),
        migrations.AddIndex(
            model_name='situationtravaux',
            index=models.Index(fields=['status', 'affaire'], name='operations__status_740c42_idx'),
        ),
    ]
