# Generated by Django 5.2.17 on 2026-09-21 16:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connector', models.CharField(choices=[('partners', 'Tiers (CSV)'), ('gl', 'Écritures générales (CSV — reprise SAGE)'), ('cfonb', 'Relevés bancaires CFONB'), ('mt940', 'Relevé bancaire SWIFT MT940'), ('cnssg', 'Cotisations CNSSG'), ('cnamgs', 'Cotisations CNAMGS'), ('generic', 'Table générique')], db_index=True, max_length=12, verbose_name='Connecteur')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('success', 'Succès'), ('partial', 'Partiel (erreurs)'), ('failed', 'Échoué')], default='pending', max_length=8, verbose_name='Statut')),
                ('filename', models.CharField(max_length=255, verbose_name='Fichier')),
                ('file_hash', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Lignes')),
                ('created_rows', models.PositiveIntegerField(default=0, verbose_name='Créées')),
                ('updated_rows', models.PositiveIntegerField(default=0, verbose_name='Mises à jour')),
                ('error_rows', models.PositiveIntegerField(default=0, verbose_name='En erreur')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur global")),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Lot d'import",
                'verbose_name_plural': "Lots d'import",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField(verbose_name='N° de ligne')),
                ('status', models.CharField(choices=[('success', 'Traitée'), ('duplicate', 'Déjà présente (écartée)'), ('error', 'En erreur')], max_length=10, verbose_name='Statut')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Données')),
                ('error_message', models.TextField(blank=True, verbose_name='Erreur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='integrations.importbatch', verbose_name='Lot')),
            ],
            options={
                'verbose_name': "Ligne d'import",
                'verbose_name_plural': "Lignes d'import",
                'ordering': ['batch', 'row_number'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'row_number'), name='uniq_batchrow_number')],
            },
        ),
    ]
