# Generated by Django 5.2.17 on 2026-09-22 17:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0001_initial'),
        ('operations', '0001_initial'),
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualiteSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10, unique=True, verbose_name='Type')),
                ('prefix', models.CharField(max_length=10, verbose_name='Préfixe')),
                ('padding', models.PositiveSmallIntegerField(default=5, verbose_name='Zéro-padding')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Prochain numéro')),
            ],
            options={
                'verbose_name': 'Séquence Qualité',
                'verbose_name_plural': 'Séquences Qualité',
            },
        ),
        migrations.CreateModel(
            name='Soudeur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('prenoms', models.CharField(blank=True, max_length=150, verbose_name='Prénoms')),
                ('matricule', models.CharField(blank=True, max_length=60, verbose_name='Matricule')),
                ('qualification', models.CharField(blank=True, max_length=120, verbose_name='Qualification principale')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Soudeur',
                'verbose_name_plural': 'Soudeurs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ControleQualite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('type_controle', models.CharField(choices=[('visuel', 'Contrôle visuel'), ('dimensionnel', 'Contrôle dimensionnel'), ('cnd', 'CND (radiographie, ultrasons, ressuage, magnétoscopie)'), ('pda', 'PDA (plan de détection)'), ('itp', "ITP (plan d'inspection et d'essais)"), ('peinture', 'Peinture / anticorrosion')], default='visuel', max_length=14, verbose_name='Type de contrôle')),
                ('organisme', models.CharField(choices=[('interne', 'Interne QA/QC'), ('agrege', 'Organisme agréé')], default='interne', max_length=14, verbose_name='Réalisé par')),
                ('organisme_libelle', models.CharField(blank=True, max_length=150, verbose_name='Organisme (si agréé)')),
                ('point_controle', models.CharField(blank=True, max_length=200, verbose_name='Point de contrôle (repère / joint)')),
                ('exigence', models.CharField(blank=True, max_length=200, verbose_name="Exigence / critère d'acceptation")),
                ('date_controle', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date du contrôle')),
                ('resultat', models.CharField(choices=[('conforme', 'Conforme'), ('reserve', 'Accepté sous réserve'), ('non_conforme', 'Non conforme')], default='conforme', max_length=14, verbose_name='Résultat')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('valide', 'Validé'), ('annule', 'Annulé')], default='en_attente', max_length=12, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controles_qualite', to='commercial.affaire', verbose_name='Affaire')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualite_controles', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_qualite', to='stocks.lotmatiere', verbose_name='Lot matière contrôlé')),
                ('ordre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controles_qualite', to='operations.ordrefabrication', verbose_name='Ordre de fabrication')),
            ],
            options={
                'verbose_name': 'Contrôle qualité',
                'verbose_name_plural': 'Contrôles qualité',
                'ordering': ['-date_controle', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NonConformite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('source', models.CharField(choices=[('controle', 'Contrôle qualité'), ('client', 'Client'), ('fournisseur', 'Fournisseur'), ('interne', 'Interne')], default='controle', max_length=14, verbose_name='Source')),
                ('gravite', models.CharField(choices=[('mineure', 'Mineure'), ('majeure', 'Majeure'), ('critique', 'Critique')], default='mineure', max_length=10, verbose_name='Gravité')),
                ('description', models.TextField(verbose_name='Description')),
                ('traitement', models.CharField(choices=[('reprise', 'Reprise'), ('reparation', 'Réparation'), ('rejet', 'Rejet'), ('acceptation', 'Acceptation sous réserve'), ('arbitrage', 'Arbitrage technique')], default='reprise', max_length=14, verbose_name='Traitement')),
                ('statut', models.CharField(choices=[('signalee', 'Signalée'), ('analysee', 'Analysée'), ('en_traitement', 'En traitement'), ('cloturee', 'Clôturée')], default='signalee', max_length=14, verbose_name='Statut')),
                ('date_decision', models.DateField(blank=True, null=True, verbose_name='Date de décision')),
                ('archive', models.BooleanField(default=False, verbose_name='Archivée (10 ans Oil & Gas)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('controle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='non_conformites', to='qualite.controlequalite', verbose_name="Contrôle d'origine")),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualite_nc_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Décision QA/QC')),
            ],
            options={
                'verbose_name': 'Non-conformité',
                'verbose_name_plural': 'Non-conformités',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionCorrective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('type', models.CharField(choices=[('corrective', 'Corrective'), ('preventive', 'Préventive')], default='corrective', max_length=12, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Action')),
                ('echeance', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_cours', 'En cours'), ('cloturee', 'Clôturée')], default='ouverte', max_length=10, verbose_name='Statut')),
                ('efficace', models.BooleanField(blank=True, null=True, verbose_name='Efficacité vérifiée')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Clôturée le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualite_capa_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('non_conformite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_correctives', to='qualite.nonconformite', verbose_name='Non-conformité')),
            ],
            options={
                'verbose_name': 'Action corrective',
                'verbose_name_plural': 'Actions correctives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PvControle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('intitule', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('date_pv', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date du PV')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('reserve', 'Sous réserve'), ('receptionne', 'Réceptionné / levée de réserve'), ('rejete', 'Rejeté')], default='en_cours', max_length=12, verbose_name='Statut')),
                ('resultat', models.CharField(choices=[('conforme', 'Conforme'), ('reserve', 'Accepté sous réserve'), ('non_conforme', 'Non conforme')], default='conforme', max_length=14, verbose_name='Résultat global')),
                ('reserve_motif', models.TextField(blank=True, verbose_name='Motif de réserve (si réservé)')),
                ('levee_reserve', models.DateField(blank=True, null=True, verbose_name='Levée de réserve')),
                ('retention_years', models.PositiveSmallIntegerField(default=10, verbose_name='Conservation (années)')),
                ('date_archivage', models.DateField(blank=True, null=True, verbose_name="Date d'archivage")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pv_controle', to='commercial.affaire', verbose_name='Affaire')),
                ('controles', models.ManyToManyField(blank=True, related_name='pvs', to='qualite.controlequalite', verbose_name='Contrôles couverts')),
                ('ordre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pv_controle', to='operations.ordrefabrication', verbose_name='Ordre de fabrication')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualite_pv_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'PV de contrôle',
                'verbose_name_plural': 'PV de contrôle',
                'ordering': ['-date_pv'],
            },
        ),
        migrations.CreateModel(
            name='QualificationSoudeur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('norme', models.CharField(choices=[('iso9606', 'ISO 9606-1'), ('asme_ix', 'ASME IX')], default='iso9606', max_length=12, verbose_name='Norme')),
                ('procede', models.CharField(choices=[('smaw', 'SMAW (électrode enrobée)'), ('gtaw', 'GTAW (TIG)'), ('gmaw', 'GMAW (MIG/MAG)'), ('fcaw', 'FCAW (fil fourré)')], default='smaw', max_length=6, verbose_name='Procédé')),
                ('position', models.CharField(blank=True, max_length=60, verbose_name='Position(s)')),
                ('groupe_materiaux', models.CharField(blank=True, max_length=120, verbose_name='Groupe de matériaux')),
                ('epaisseur_min', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Épaisseur min (mm)')),
                ('epaisseur_max', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Épaisseur max (mm)')),
                ('gamme_diametre', models.CharField(blank=True, max_length=120, verbose_name='Gamme diamètre (tubes)')),
                ('date_qualification', models.DateField(verbose_name='Date de qualification')),
                ('date_validite', models.DateField(verbose_name='Date de validité')),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('expiree', 'Expirée'), ('suspendue', 'Suspendue')], default='valide', max_length=12, verbose_name='Statut')),
                ('certificat', models.CharField(blank=True, max_length=80, verbose_name='N° certificat')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soudeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='qualite.soudeur', verbose_name='Soudeur')),
            ],
            options={
                'verbose_name': 'Qualification soudeur',
                'verbose_name_plural': 'Qualifications soudeurs',
                'ordering': ['-date_validite'],
            },
        ),
        migrations.CreateModel(
            name='WpsWpqr',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('type', models.CharField(choices=[('wps', 'WPS (procédure de soudage)'), ('wpqr', 'WPQR (qualification mode opératoire)')], default='wps', max_length=5, verbose_name='Type')),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='Référence')),
                ('norme', models.CharField(choices=[('iso9606', 'ISO 9606-1'), ('asme_ix', 'ASME IX')], default='iso9606', max_length=12, verbose_name='Norme')),
                ('procede', models.CharField(choices=[('smaw', 'SMAW (électrode enrobée)'), ('gtaw', 'GTAW (TIG)'), ('gmaw', 'GMAW (MIG/MAG)'), ('fcaw', 'FCAW (fil fourré)')], default='smaw', max_length=6, verbose_name='Procédé')),
                ('materiau', models.CharField(blank=True, max_length=120, verbose_name='Matériau de base')),
                ('position', models.CharField(blank=True, max_length=60, verbose_name='Position(s)')),
                ('epaisseur', models.CharField(blank=True, max_length=120, verbose_name='Épaisseur / diamètre')),
                ('gaz_protection', models.CharField(blank=True, max_length=120, verbose_name='Gaz de protection')),
                ('parametres', models.JSONField(blank=True, default=dict, verbose_name='Paramètres de soudage')),
                ('revue', models.CharField(blank=True, max_length=60, verbose_name='Revue')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('obsolete', 'Obsolète')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('date_validation', models.DateField(blank=True, null=True, verbose_name='Date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualite_wps_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validé par QA/QC')),
            ],
            options={
                'verbose_name': 'WPS / WPQR',
                'verbose_name_plural': 'WPS / WPQR',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='controlequalite',
            name='wps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles', to='qualite.wpswpqr', verbose_name='WPS'),
        ),
        migrations.AddIndex(
            model_name='nonconformite',
            index=models.Index(fields=['statut', 'gravite'], name='qualite_non_statut_9520c4_idx'),
        ),
        migrations.AddIndex(
            model_name='qualificationsoudeur',
            index=models.Index(fields=['soudeur', 'norme'], name='qualite_qua_soudeur_8e3de6_idx'),
        ),
        migrations.AddIndex(
            model_name='controlequalite',
            index=models.Index(fields=['type_controle', 'resultat'], name='qualite_con_type_co_291893_idx'),
        ),
    ]
