# Generated by Django 5.2.17 on 2026-09-22 19:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistique', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10, unique=True, verbose_name='Type')),
                ('prefix', models.CharField(max_length=10, verbose_name='Préfixe')),
                ('padding', models.PositiveSmallIntegerField(default=5, verbose_name='Zéro-padding')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Prochain numéro')),
            ],
            options={
                'verbose_name': 'Séquence Maintenance',
                'verbose_name_plural': 'Séquences Maintenance',
            },
        ),
        migrations.CreateModel(
            name='Actif',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('categorie', models.CharField(choices=[('machine', 'Machine / poste de soudage'), ('engin', 'Engin / engin de chantier'), ('levage', 'Appareil de levage'), ('atelier', "Équipement d'atelier"), ('chantier', 'Équipement de chantier'), ('outillage', 'Outillage')], default='machine', max_length=10, verbose_name='Catégorie')),
                ('fabricant', models.CharField(blank=True, max_length=120, verbose_name='Fabricant')),
                ('modele', models.CharField(blank=True, max_length=120, verbose_name='Modèle')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='N° de série')),
                ('site', models.CharField(blank=True, max_length=120, verbose_name='Site / dépôt')),
                ('statut', models.CharField(choices=[('operationnel', 'Opérationnel'), ('en_maintenance', 'En maintenance'), ('en_panne', 'En panne'), ('hors_service', 'Hors service'), ('reforme', 'Réformé')], default='operationnel', max_length=14, verbose_name='Statut')),
                ('date_mise_en_service', models.DateField(blank=True, null=True, verbose_name='Mise en service')),
                ('garanti_jusqu', models.DateField(blank=True, null=True, verbose_name="Garantie jusqu'au")),
                ('compteur_type', models.CharField(choices=[('heures', 'Heures moteur'), ('km', 'Kilomètres'), ('aucun', 'Sans compteur')], default='heures', max_length=7, verbose_name='Type de compteur')),
                ('compteur_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valeur compteur')),
                ('is_global_rental', models.BooleanField(default=False, verbose_name='Équipement GLOBAL RENTAL (GR)')),
                ('signe_618', models.BooleanField(default=False, help_text='Coût/Gain GR isolé au compte 618 (SYSCOHADA).', verbose_name='Refacturation compte 618')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipement_gr', models.ForeignKey(blank=True, help_text='Compteur lu en lecture seule depuis la logistique (RF-ERP-72).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_actifs', to='logistique.equipementparc', verbose_name='Équipement GLOBAL RENTAL lié')),
            ],
            options={
                'verbose_name': 'Actif (machine / équipement)',
                'verbose_name_plural': 'Actifs — parc machines & équipements',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OrdreTravail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('type_ot', models.CharField(choices=[('correctif', 'Correctif'), ('preventif', 'Préventif'), ('urgence', 'Urgence / dépannage'), ('inspection', 'Inspection')], default='correctif', max_length=11, verbose_name='Type')),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('critique', 'Critique')], default='moyenne', max_length=10, verbose_name='Priorité')),
                ('description', models.TextField(verbose_name="Description de l'intervention")),
                ('cause', models.TextField(blank=True, verbose_name='Cause / diagnostic')),
                ('date_demande', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de demande')),
                ('date_planifiee', models.DateField(blank=True, null=True, verbose_name='Date planifiée')),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name="Début d'intervention")),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name="Fin d'intervention")),
                ('heures_mo', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name="Heures main-d'œuvre")),
                ('tarif_horaire', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tarif horaire (FCFA)')),
                ('cout_pieces', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Coût pièces (FCFA)')),
                ('decision', models.CharField(blank=True, choices=[('reparation', 'Réparation lourde'), ('mise_hors_service', 'Mise hors service'), ('reforme', 'Réforme')], max_length=18, verbose_name='Décision')),
                ('rapport', models.TextField(blank=True, verbose_name="Rapport d'intervention")),
                ('statut', models.CharField(choices=[('demande', 'Demandé'), ('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('cloture', 'Clôturé'), ('annule', 'Annulé')], default='demande', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordres_travail', to='maintenance.actif', verbose_name='Équipement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_ot_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_ot_demandes', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_ot_interventions', to=settings.AUTH_USER_MODEL, verbose_name='Technicien')),
            ],
            options={
                'verbose_name': 'Ordre de travail (OT)',
                'verbose_name_plural': 'Ordres de travail — GMAO',
                'ordering': ['-date_demande', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('type_inspection', models.CharField(choices=[('visuelle', 'Visuelle'), ('fonctionnelle', 'Fonctionnelle'), ('securite', 'Sécurité'), ('levage', 'Appareil de levage'), ('atex', 'ATEX'), ('metrologie', 'Métrologie / étalonnage')], default='visuelle', max_length=14, verbose_name='Type')),
                ('date_inspection', models.DateField(verbose_name="Date d'inspection")),
                ('prochaine_inspection', models.DateField(blank=True, null=True, verbose_name='Prochaine inspection')),
                ('organisme', models.CharField(default='interne', max_length=60, verbose_name='Organisme')),
                ('organisme_libelle', models.CharField(blank=True, max_length=120, verbose_name='Organisme (libellé)')),
                ('resultat', models.CharField(blank=True, choices=[('conforme', 'Conforme'), ('sous_reserve', 'Sous réserve'), ('non_conforme', 'Non conforme')], max_length=14, verbose_name='Résultat')),
                ('constat', models.TextField(blank=True, verbose_name='Constat / observations')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('realisee', 'Réalisée'), ('annulee', 'Annulée')], default='planifiee', max_length=12, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='maintenance.actif', verbose_name='Équipement')),
                ('intervenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Inspécteur')),
                ('ot_genere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_source', to='maintenance.ordretravail', verbose_name='OT généré')),
            ],
            options={
                'verbose_name': 'Inspection périodique',
                'verbose_name_plural': 'Inspections périodiques',
                'ordering': ['-date_inspection'],
            },
        ),
        migrations.AddIndex(
            model_name='actif',
            index=models.Index(fields=['statut', 'categorie'], name='maintenance_statut_74fd20_idx'),
        ),
        migrations.AddIndex(
            model_name='ordretravail',
            index=models.Index(fields=['type_ot', 'statut'], name='maintenance_type_ot_f32726_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['type_inspection', 'statut'], name='maintenance_type_in_b90b25_idx'),
        ),
    ]
