# Generated by Django 5.2.17 on 2026-09-22 21:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RhPaieSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10, unique=True, verbose_name='Type')),
                ('prefix', models.CharField(max_length=10, verbose_name='Préfixe')),
                ('padding', models.PositiveSmallIntegerField(default=5, verbose_name='Zéro-padding')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Prochain numéro')),
            ],
            options={
                'verbose_name': 'Séquence RH & Paie',
                'verbose_name_plural': 'Séquences RH & Paie',
            },
        ),
        migrations.CreateModel(
            name='RubriquePaie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=150, verbose_name='Libellé')),
                ('nature', models.CharField(choices=[('gain', 'Gain (rémunération)'), ('retenue', 'Retenue / cotisation')], default='gain', max_length=10, verbose_name='Nature')),
                ('base', models.CharField(choices=[('fixe', 'Montant fixe'), ('salaire', '% du salaire de base'), ('brut', '% du brut')], default='fixe', max_length=10, verbose_name='Base de calcul')),
                ('taux', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Taux (%) si base %')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Rubrique de paie',
                'verbose_name_plural': 'Rubriques de paie',
                'ordering': ['nature', 'ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DemandeRecrutement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('poste', models.CharField(max_length=150, verbose_name='Poste à pourvoir')),
                ('type', models.CharField(choices=[('creation', 'Création de poste'), ('remplacement', 'Remplacement'), ('renfort', 'Renfort temporaire'), ('chantier', 'Besoin chantier')], default='creation', max_length=12, verbose_name='Type de besoin')),
                ('justification', models.TextField(verbose_name='Justification du besoin')),
                ('date_souhaitee', models.DateField(blank=True, null=True, verbose_name='Prise de poste souhaitée')),
                ('statut', models.CharField(choices=[('demande', 'Demandé'), ('validee', 'Besoin validé'), ('candidats', 'Sélection candidats'), ('entrevue', 'Entretiens'), ('integre', 'Candidat intégré'), ('annulee', 'Annulée')], default='demande', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rh_recrutements', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Demande de recrutement',
                'verbose_name_plural': 'Demandes de recrutement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('civilite', models.CharField(choices=[('masculin', 'Masculin'), ('feminin', 'Féminin')], max_length=14, verbose_name='Civilité')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=150, verbose_name='Prénom')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=120, verbose_name='Lieu de naissance')),
                ('nationalite', models.CharField(blank=True, max_length=80, verbose_name='Nationalité')),
                ('numero_securite_sociale', models.CharField(blank=True, max_length=40, verbose_name='N° sécurité sociale (CNSS)')),
                ('telephone', models.CharField(blank=True, max_length=40, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email personnel')),
                ('adresse', models.CharField(blank=True, max_length=200, verbose_name='Adresse')),
                ('categorie', models.CharField(choices=[('cadre', 'Cadre'), ('agent_maitrise', 'Agent de maîtrise'), ('technicien', 'Technicien'), ('ouvrier', 'Ouvrier / chantier')], default='ouvrier', max_length=20, verbose_name='Catégorie')),
                ('fonction', models.CharField(blank=True, max_length=150, verbose_name='Fonction')),
                ('departement', models.CharField(blank=True, max_length=120, verbose_name='Département')),
                ('site', models.CharField(blank=True, max_length=120, verbose_name='Site / affectation')),
                ('statut', models.CharField(choices=[('actif', 'En poste'), ('conge', 'En congé / rotation'), ('suspendu', 'Suspendu'), ('sorti', 'Sorti')], default='actif', max_length=10, verbose_name='Statut')),
                ('matricule_cnps', models.CharField(blank=True, max_length=40, verbose_name='Matricule CNAMGS')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('date_sortie', models.DateField(blank=True, null=True, verbose_name='Date de sortie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employé (dossier RH)',
                'verbose_name_plural': 'Employés — dossiers RH',
                'ordering': ['nom', 'prenom'],
                'indexes': [models.Index(fields=['statut', 'departement'], name='rh_paie_emp_statut_ce040c_idx')],
            },
        ),
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('periode', models.DateField(verbose_name='Période (1er du mois)')),
                ('salaire_base', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Salaire de base (FCFA)')),
                ('brut', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Brut (FCFA)')),
                ('net', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Net à payer (FCFA)')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('cloture', 'Clôturé'), ('annule', 'Annulé')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletins', to='rh_paie.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Bulletin de paie',
                'verbose_name_plural': 'Bulletins de paie',
                'ordering': ['-periode', 'employe__nom'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('theme', models.CharField(max_length=180, verbose_name='Thème')),
                ('organisme', models.CharField(blank=True, max_length=120, verbose_name='Organisme')),
                ('formateur', models.CharField(blank=True, max_length=120, verbose_name='Formateur')),
                ('date_session', models.DateField(verbose_name='Date de session')),
                ('duree_heures', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Durée (heures)')),
                ('type', models.CharField(choices=[('planifie', 'Prévue'), ('realisee', 'Réalisée'), ('annulee', 'Annulée')], default='planifie', max_length=12, verbose_name='Statut')),
                ('evaluation', models.CharField(blank=True, max_length=400, verbose_name='Évaluation post-formation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='formations', to='rh_paie.employe', verbose_name='Participants')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations & développement des compétences',
                'ordering': ['-date_session'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('type', models.CharField(choices=[('habilitation', 'Habilitation'), ('permis', 'Permis / carte professionnelle'), ('certificat', 'Certificat / attestation'), ('diplome', 'Diplôme')], default='habilitation', max_length=14, verbose_name='Type')),
                ('intitule', models.CharField(max_length=180, verbose_name='Intitulé')),
                ('organisme', models.CharField(blank=True, max_length=120, verbose_name='Organisme délivrant')),
                ('date_obtention', models.DateField(blank=True, null=True, verbose_name="Date d'obtention")),
                ('date_validite', models.DateField(blank=True, null=True, verbose_name='Date de validité')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualifications', to='rh_paie.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Qualification / habilitation',
                'verbose_name_plural': 'Qualifications & habilitations',
                'ordering': ['-date_validite'],
            },
        ),
        migrations.CreateModel(
            name='BulletinLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150, verbose_name='Libellé')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant (FCFA)')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='rh_paie.bulletinpaie', verbose_name='Bulletin')),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rh_paie.rubriquepaie', verbose_name='Rubrique')),
            ],
            options={
                'verbose_name': 'Ligne de bulletin',
                'verbose_name_plural': 'Lignes de bulletins',
                'ordering': ['rubrique__nature', 'rubrique__ordre'],
            },
        ),
        migrations.CreateModel(
            name='SaisieTemps',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('date', models.DateField(verbose_name='Date')),
                ('heures', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Heures')),
                ('type', models.CharField(choices=[('normal', 'Heures normales'), ('supplementaire', 'Heures supplémentaires'), ('nuit', 'Heures de nuit'), ('astreinte', 'Astreinte')], default='normal', max_length=14, verbose_name='Type')),
                ('source', models.CharField(default='saisie', max_length=20, verbose_name='Source')),
                ('statut', models.CharField(choices=[('saisi', 'Saisi'), ('transfere', 'Transféré en paie')], default='saisi', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saisies_temps', to='rh_paie.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Saisie temps / pointage',
                'verbose_name_plural': 'Pointages & saisie temps',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('type', models.CharField(choices=[('rappel', "Rappel à l'ordre"), ('avertissement', 'Avertissement'), ('mise_a_pied', 'Mise à pied'), ('suspension', 'Suspension'), ('licenciement', 'Licenciement'), ('autre', 'Autre mesure')], default='avertissement', max_length=16, verbose_name='Type de sanction')),
                ('faits', models.TextField(verbose_name='Faits reprochés')),
                ('rapport', models.TextField(blank=True, verbose_name='Rapport disciplinaire')),
                ('date_constat', models.DateField(verbose_name='Date de constat')),
                ('date_decision', models.DateField(blank=True, null=True, verbose_name='Date de décision')),
                ('statut', models.CharField(choices=[('constate', 'Constaté'), ('instruite', 'En instruction'), ('decidee', 'Décision prise'), ('archivee', 'Archivée')], default='constate', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanctions', to='rh_paie.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Sanction disciplinaire',
                'verbose_name_plural': 'Discipline & sanctions',
                'ordering': ['-date_constat'],
            },
        ),
        migrations.CreateModel(
            name='DemandesConge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('type', models.CharField(choices=[('annuel', 'Congé annuel'), ('rotation', 'Rotation / rapatriement'), ('maladie', 'Congé maladie'), ('maternite', 'Congé maternité'), ('sans_solde', 'Congé sans solde'), ('exceptionnel', 'Congé exceptionnel')], default='annuel', max_length=14, verbose_name='Type')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('nb_jours', models.PositiveIntegerField(verbose_name='Nombre de jours')),
                ('motif', models.CharField(blank=True, max_length=200, verbose_name='Motif / commentaire')),
                ('statut', models.CharField(choices=[('demande', 'Demandé'), ('approuve', 'Approuvé hiérarchie'), ('valide', 'Validé RH'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='demande', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_conges', to='rh_paie.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Congés & rotations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['statut', 'date_debut'], name='rh_paie_dem_statut_1754c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContratTravail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('type', models.CharField(choices=[('cdd', 'CDD'), ('cdi', 'CDI'), ('chantier', 'Contrat de chantier'), ('mission', 'Mission / intérim'), ('stage', 'Stage / apprentissage')], default='cdd', max_length=12, verbose_name='Type')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin (CDD)')),
                ('salaire_base', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Salaire de base (FCFA)')),
                ('regime_horaire', models.CharField(blank=True, max_length=40, verbose_name='Régime horaire')),
                ('lieu_affectation', models.CharField(blank=True, max_length=120, verbose_name="Lieu d'affectation")),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('essai', "Période d'essai"), ('expire', 'Expiré'), ('resilie', 'Résilié')], default='actif', max_length=8, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / avenants')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='rh_paie.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Contrat de travail',
                'verbose_name_plural': 'Contrats de travail',
                'ordering': ['-date_debut'],
                'indexes': [models.Index(fields=['type', 'statut'], name='rh_paie_con_type_06a7a6_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='bulletinpaie',
            constraint=models.UniqueConstraint(fields=('employe', 'periode'), name='uniq_employe_periode'),
        ),
        migrations.AddConstraint(
            model_name='bulletinligne',
            constraint=models.UniqueConstraint(fields=('bulletin', 'rubrique'), name='uniq_bulletin_rubrique'),
        ),
        migrations.AddIndex(
            model_name='saisietemps',
            index=models.Index(fields=['date', 'statut'], name='rh_paie_sai_date_842847_idx'),
        ),
        migrations.AddIndex(
            model_name='sanction',
            index=models.Index(fields=['type', 'statut'], name='rh_paie_san_type_1ddd42_idx'),
        ),
    ]
