# Generated by Django 5.2.17 on 2026-09-22 22:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting_kernel', '0001_initial'),
        ('achats', '0001_initial'),
        ('referentiels', '0002_currency_unitofmeasure_account_analyticaxis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComptabiliteSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10, unique=True, verbose_name='Type')),
                ('prefix', models.CharField(max_length=10, verbose_name='Préfixe')),
                ('padding', models.PositiveSmallIntegerField(default=5, verbose_name='Zéro-padding')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Prochain numéro')),
            ],
            options={
                'verbose_name': 'Séquence Comptabilité',
                'verbose_name_plural': 'Séquences Comptabilité',
            },
        ),
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=200, verbose_name='Désignation')),
                ('banque', models.CharField(max_length=120, verbose_name='Banque')),
                ('numero', models.CharField(blank=True, max_length=80, verbose_name='N° de compte / IBAN')),
                ('solde_initial', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Solde initial')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compte_comptable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comptes_bancaires', to='referentiels.account', verbose_name='Compte comptable (512x)')),
                ('devise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_bancaires', to='referentiels.currency', verbose_name='Devise')),
            ],
            options={
                'verbose_name': 'Compte bancaire',
                'verbose_name_plural': 'Comptes bancaires',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ControleInterne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=250, verbose_name='Point de contrôle')),
                ('reference_procedure', models.CharField(blank=True, max_length=40, verbose_name='Réf. procédure (proc. 4.x)')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('realise', 'Réalisé'), ('cloture', 'Clôturé')], default='planifie', max_length=10, verbose_name='Statut')),
                ('date_prevue', models.DateField(blank=True, null=True, verbose_name='Date prévue')),
                ('date_realise', models.DateField(blank=True, null=True, verbose_name='Date de réalisation')),
                ('constat', models.TextField(blank=True, verbose_name='Constat / observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_internes', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Contrôle interne',
                'verbose_name_plural': 'Contrôles internes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('objet', models.CharField(max_length=250, verbose_name='Objet de la dépense')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Montant')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis pour visa'), ('approuve', 'Approuvé'), ('annule', 'Annulé')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('date_engagement', models.DateField(blank=True, null=True, verbose_name="Date d'engagement")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compte_depense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='referentiels.account', verbose_name='Compte de dépense (6xx)')),
                ('demande_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements_demandes', to=settings.AUTH_USER_MODEL, verbose_name='Demandé par')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements', to='referentiels.partner', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Engagement de dépense',
                'verbose_name_plural': 'Engagements de dépense',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('sens', models.CharField(choices=[('sortie', 'Décaissement (fournisseur)'), ('entree', 'Encaissement (client / cession)')], max_length=8, verbose_name='Sens')),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('cfonb', 'CFONB / MT940'), ('autre', 'Autre')], max_length=10, verbose_name='Mode')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Montant')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de paiement')),
                ('imputation_618', models.BooleanField(default=False, verbose_name='Refacturation intra-groupe (compte 618)')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='Référence')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('annule', 'Annulé')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compte_bancaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='comptabilite.comptebancaire', verbose_name='Compte bancaire')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_m10', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='comptabilite.engagement', verbose_name='Engagement')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='achats.purchaseinvoice', verbose_name='Facture fournisseur')),
                ('move', models.ForeignKey(blank=True, help_text='Écriture générée à la validation (noyau comptable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_m10', to='accounting_kernel.accountmove', verbose_name='Écriture comptable')),
                ('tiers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='referentiels.partner', verbose_name='Tiers')),
            ],
            options={
                'verbose_name': 'Paiement / encaissement',
                'verbose_name_plural': 'Paiements / encaissements',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RapprochementBancaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compte_bancaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rapprochements', to='comptabilite.comptebancaire', verbose_name='Compte bancaire')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapprochements_bancaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapprochement bancaire',
                'verbose_name_plural': 'Rapprochements bancaires',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReleveBancaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('date_debut', models.DateField(verbose_name='Date début')),
                ('date_fin', models.DateField(verbose_name='Date fin')),
                ('solde_initial', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Solde initial')),
                ('solde_final', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Solde final')),
                ('statut', models.CharField(choices=[('importe', 'Importé'), ('valide', 'Validé')], default='importe', max_length=10, verbose_name='Statut')),
                ('source', models.CharField(choices=[('cfonb', 'CFONB'), ('mt940', 'MT940'), ('manuel', 'Saisie manuelle')], default='manuel', max_length=10, verbose_name='Source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compte_bancaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releves', to='comptabilite.comptebancaire', verbose_name='Compte bancaire')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releves_bancaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relevé bancaire',
                'verbose_name_plural': 'Relevés bancaires',
                'ordering': ['-date_fin'],
            },
        ),
        migrations.CreateModel(
            name='LigneReleve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('libelle', models.CharField(max_length=250, verbose_name='Libellé')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='Référence')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Débit')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Crédit')),
                ('rapprochee', models.BooleanField(default=False, verbose_name='Rapprochée')),
                ('releve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite.relevebancaire', verbose_name='Relevé')),
            ],
            options={
                'verbose_name': 'Ligne de relevé',
                'verbose_name_plural': 'Lignes de relevé',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TauxTva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=120, verbose_name='Libellé')),
                ('taux', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Taux (%)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Taux par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('compte_collecte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiels.account', verbose_name='Compte TVA collectée (44x)')),
                ('compte_deductible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiels.account', verbose_name='Compte TVA déductible (44x)')),
            ],
            options={
                'verbose_name': 'Taux de TVA',
                'verbose_name_plural': 'Taux de TVA',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LigneRapprochement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ligne_releve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapprochements', to='comptabilite.lignereleve', verbose_name='Ligne de relevé')),
                ('rapprochement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite.rapprochementbancaire', verbose_name='Rapprochement')),
            ],
            options={
                'verbose_name': 'Ligne de rapprochement',
                'verbose_name_plural': 'Lignes de rapprochement',
                'constraints': [models.UniqueConstraint(fields=('rapprochement', 'ligne_releve'), name='uniq_rapprochement_ligne_releve')],
            },
        ),
        migrations.CreateModel(
            name='DeclarationTva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('mois', models.DateField(help_text='Premier jour du mois concerné.', verbose_name='Période')),
                ('base_imposable', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Base imposable (HT)')),
                ('tva_collectee', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='TVA collectée')),
                ('tva_deductible', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='TVA déductible')),
                ('net_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='TVA nette à payer')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('deposee', 'Déposée')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_tva', to=settings.AUTH_USER_MODEL)),
                ('taux_tva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='comptabilite.tauxtva', verbose_name='Taux de TVA')),
            ],
            options={
                'verbose_name': 'Déclaration TVA',
                'verbose_name_plural': 'Déclarations TVA',
                'ordering': ['-mois'],
                'constraints': [models.UniqueConstraint(fields=('mois', 'taux_tva'), name='uniq_tva_mois_taux')],
            },
        ),
    ]
