# Generated by Django 5.2.17 on 2026-09-21 18:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0006_document_extracted_text_document_search_vector_and_more'),
        ('referentiels', '0002_currency_unitofmeasure_account_analyticaxis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10, unique=True, verbose_name='Type')),
                ('prefix', models.CharField(max_length=10, verbose_name='Préfixe')),
                ('padding', models.PositiveSmallIntegerField(default=5, verbose_name='Zéro-padding')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Prochain numéro')),
            ],
            options={
                'verbose_name': 'Séquence Commercial',
                'verbose_name_plural': 'Séquences Commercial',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segment', models.CharField(choices=[('petrole_gaz', 'Pétrole & Gaz'), ('industrie', 'Industrie'), ('construction', 'BTP / Construction'), ('mines', 'Mines'), ('admin_pub', 'Administration publique'), ('particulier', 'Particulier'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Segment')),
                ('scoring', models.PositiveSmallIntegerField(default=0, verbose_name='Score client (0-100)')),
                ('origin', models.CharField(choices=[('appel_offres', "Appel d'offres"), ('relation', 'Relation commerciale'), ('prospection', 'Prospection'), ('marche', 'Marché existant')], default='relation', max_length=20, verbose_name='Origine')),
                ('contacts', models.JSONField(blank=True, default=dict, verbose_name='Contacts')),
                ('history', models.JSONField(blank=True, default=list, verbose_name='Historique / mémoire')),
                ('last_contact', models.DateField(blank=True, null=True, verbose_name='Dernier contact')),
                ('next_contact', models.DateField(blank=True, null=True, verbose_name='Prochain contact')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_profile', to='referentiels.partner', verbose_name='Tiers')),
            ],
            options={
                'verbose_name': 'Client (mémoire CRM)',
                'verbose_name_plural': 'Clients (mémoire CRM)',
                'ordering': ['-scoring', 'partner__name'],
            },
        ),
        migrations.CreateModel(
            name='Affaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('title', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('affaire_type', models.CharField(choices=[('chantier', 'Chantier'), ('atelier', 'Atelier'), ('maintenance', 'Maintenance'), ('fourniture', 'Fourniture')], default='atelier', max_length=12, verbose_name='Type')),
                ('contract_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant contractuel')),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Marge')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('confirmee', 'Confirmée'), ('en_cours', 'En cours'), ('cloturee', 'Clôturée'), ('archivee', 'Archivée')], default='brouillon', max_length=12, verbose_name='Statut')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('is_global_rental', models.BooleanField(default=False, verbose_name='GLOBAL RENTAL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiels.currency', verbose_name='Devise')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affaires', to='commercial.clientprofile', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Affaire',
                'verbose_name_plural': 'Affaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('profile', models.CharField(choices=[('marche_travaux', 'Marché de travaux'), ('maintenance', 'Contrat de maintenance')], max_length=14, verbose_name='Profil contractuel')),
                ('start_date', models.DateField(verbose_name='Début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('months', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Durée (mois)')),
                ('amount_initial', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant initial')),
                ('sla', models.CharField(blank=True, max_length=200, verbose_name='SLA (maintenance)')),
                ('retenue_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux de retenue (%)')),
                ('indexation', models.BooleanField(default=False, verbose_name="Clause d'indexation")),
                ('penalty', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Pénalités')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('actif', 'Actif'), ('suspendu', 'Suspendu'), ('cloture', 'Clôturé')], default='brouillon', max_length=12, verbose_name='Statut')),
                ('is_global_rental', models.BooleanField(default=False, verbose_name='GLOBAL RENTAL')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='commercial.affaire', verbose_name='Affaire')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='commercial.clientprofile', verbose_name='Client')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiels.currency', verbose_name='Devise')),
            ],
            options={
                'verbose_name': 'Contrat (CLM)',
                'verbose_name_plural': 'Contrats (CLM)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200, verbose_name='Prestation')),
                ('kind', models.CharField(choices=[('forfait', 'Forfait'), ('variable', 'Variable'), ('sla', 'SLA / réactif')], default='forfait', max_length=10, verbose_name='Type')),
                ('sla_hours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='SLA (heures)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Prix')),
                ('frequency', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel')], default='mensuel', max_length=12, verbose_name='Facturation')),
                ('is_global_rental', models.BooleanField(default=False, verbose_name='GLOBAL RENTAL')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='commercial.contract', verbose_name='Contrat')),
            ],
            options={
                'verbose_name': 'Prestation de contrat',
                'verbose_name_plural': 'Prestations de contrat',
                'ordering': ['contract', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('title', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('gagnee', 'Gagnée'), ('perdue', 'Perdue'), ('annulee', 'Annulée')], default='brouillon', max_length=12, verbose_name='Statut')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total')),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Marge prévue')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="Validité de l'offre")),
                ('is_global_rental', models.BooleanField(default=False, verbose_name='Prestation GLOBAL RENTAL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='commercial.clientprofile', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_estimates', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_estimates', to='referentiels.currency', verbose_name='Devise')),
            ],
            options={
                'verbose_name': 'Chiffrage / Offre',
                'verbose_name_plural': 'Chiffrages / Offres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200, verbose_name='Désignation')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=14, verbose_name='Qté')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Prix unitaire')),
                ('price_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total ligne')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_lines', to='referentiels.article', verbose_name='Article')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='commercial.estimate', verbose_name='Chiffrage')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiels.unitofmeasure', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Ligne de chiffrage',
                'verbose_name_plural': 'Lignes de chiffrage',
                'ordering': ['estimate', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EstimateOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200, verbose_name="Libellé de l'option")),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="Montant de l'option")),
                ('duration_months', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Durée (mois)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_selected', models.BooleanField(default=False, verbose_name='Option retenue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='commercial.estimate', verbose_name='Chiffrage')),
            ],
            options={
                'verbose_name': 'Option de chiffrage',
                'verbose_name_plural': 'Options de chiffrage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Code')),
                ('label', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('planned_date', models.DateField(verbose_name='Date prévue')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Date réelle')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Avancement (%)')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('fait', 'Réalisé'), ('retard', 'En retard'), ('skip', 'Sauté')], default='en_attente', max_length=12, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='commercial.affaire', verbose_name='Affaire')),
            ],
            options={
                'verbose_name': 'Jalon',
                'verbose_name_plural': 'Jalons',
                'ordering': ['affaire', 'planned_date'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('subject', models.CharField(max_length=200, verbose_name='Objet')),
                ('stage', models.CharField(choices=[('prospection', 'Prospection'), ('qualification', 'Qualification'), ('offre', 'Offre soumise'), ('negociation', 'Négociation'), ('gagne', 'Gagnée'), ('perdu', 'Perdue')], db_index=True, default='prospection', max_length=14, verbose_name='Étape')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant estimé')),
                ('probability', models.PositiveSmallIntegerField(default=0, verbose_name='Probabilité (%)')),
                ('expected_close', models.DateField(blank=True, null=True, verbose_name='Clôture prévue')),
                ('origin', models.CharField(choices=[('appel_offres', "Appel d'offres"), ('relation', 'Relation commerciale'), ('prospection', 'Prospection'), ('marche', 'Marché existant')], default='relation', max_length=20, verbose_name='Origine')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('won_date', models.DateField(blank=True, null=True, verbose_name='Date de gain')),
                ('lost_reason', models.CharField(blank=True, max_length=200, verbose_name='Motif de perte')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='commercial.clientprofile', verbose_name='Client')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Opportunité',
                'verbose_name_plural': 'Opportunités',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='estimate',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='commercial.opportunity', verbose_name='Opportunité'),
        ),
        migrations.AddField(
            model_name='affaire',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affaires', to='commercial.opportunity', verbose_name='Opportunité'),
        ),
        migrations.CreateModel(
            name='SoumissionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('clarification', 'Clarification'), ('negociation', 'Négociation'), ('retour', 'Retour client'), ('livraison_doc', 'Livraison document')], max_length=14, verbose_name="Type d'échange")),
                ('happened_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_soumissions', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soumission_events', to='commercial.clientprofile', verbose_name='Client')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_soumissions', to='documents.document', verbose_name='Document lié')),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soumission_events', to='commercial.estimate', verbose_name='Chiffrage')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soumission_events', to='commercial.opportunity', verbose_name='Opportunité')),
            ],
            options={
                'verbose_name': 'Échange soumission client',
                'verbose_name_plural': 'Échanges soumission client',
                'ordering': ['-happened_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tender_ref', models.CharField(blank=True, max_length=100, verbose_name="Réf. appel d'offres")),
                ('bid_deadline', models.DateField(blank=True, null=True, verbose_name='Date limite de dépôt')),
                ('review_status', models.CharField(choices=[('en_cours', 'En cours de revue'), ('pret', 'Prêt à soumettre'), ('soumis', 'Soumis'), ('archive', 'Archivé')], default='en_cours', max_length=12, verbose_name='État de revue')),
                ('requirements', models.JSONField(blank=True, default=list, verbose_name='Exigences')),
                ('decision', models.TextField(blank=True, verbose_name='Décision / suite')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revu le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tender_reviews', to='referentiels.partner', verbose_name='Client')),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tender_reviews', to='commercial.estimate', verbose_name='Chiffrage')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tender_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Revu par')),
            ],
            options={
                'verbose_name': "Revue d'appel d'offres",
                'verbose_name_plural': "Revues d'appel d'offres",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['segment', 'is_active'], name='commercial__segment_9f7198_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['stage', 'is_active'], name='commercial__stage_561a29_idx'),
        ),
    ]
