# Generated by Django 5.2.17 on 2026-09-21 15:54

import django.db.models.deletion
import django.utils.timezone
import registres.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0006_document_extracted_text_document_search_vector_and_more'),
        ('referentiels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('caisse_appro', 'Caisse & approvisionnements'), ('factures_paiements', 'Factures & paiements'), ('contrats_echeances', 'Contrats & échéances'), ('courrier', "Courrier (bureau d'ordre)"), ('incidents_hse', 'Incidents & accidents HSE'), ('stock_magasin', 'Stock & magasin'), ('conges_rotations', 'Congés & rotations'), ('formations', 'Formations & sensibilisations'), ('non_conformites', 'Non-conformités qualité')], db_index=True, max_length=30, verbose_name='Type')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé')),
                ('year', models.PositiveSmallIntegerField(default=registres.models.current_year, verbose_name='Exercice')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annexe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registres', to='referentiels.annexe', verbose_name='Annexe du MANUEL')),
            ],
            options={
                'verbose_name': 'Registre',
                'verbose_name_plural': 'Registres',
                'ordering': ['kind', '-year'],
            },
        ),
        migrations.CreateModel(
            name='RegistreEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Numéro')),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Données')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registre_entries', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registre_entries', to='documents.document', verbose_name='Document lié')),
                ('registre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='registres.registre', verbose_name='Registre')),
            ],
            options={
                'verbose_name': 'Ligne de registre',
                'verbose_name_plural': 'Lignes de registre',
                'ordering': ['registre', '-number'],
            },
        ),
        migrations.AddConstraint(
            model_name='registre',
            constraint=models.UniqueConstraint(fields=('kind', 'year'), name='uniq_registre_kind_year'),
        ),
        migrations.AddConstraint(
            model_name='registreentry',
            constraint=models.UniqueConstraint(fields=('registre', 'number'), name='uniq_registre_entry_number'),
        ),
    ]
