# Generated by Django 5.2.17 on 2026-08-10 16:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=120, verbose_name='Libellé')),
                ('retention_years', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Durée de rétention (années)')),
                ('is_restricted_rh', models.BooleanField(default=False, verbose_name='Accès restreint RH (RF-33)')),
            ],
            options={
                'verbose_name': 'Type de document',
                'verbose_name_plural': 'Types de document',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du dossier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dossiers', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='documents.dossier', verbose_name='Dossier parent')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('in_validation', 'En validation'), ('rejected', 'Rejeté'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='Statut (RF-41)')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Date du document')),
                ('counterparty', models.CharField(blank=True, max_length=200, verbose_name='Fournisseur / client')),
                ('project', models.CharField(blank=True, max_length=200, verbose_name='Projet / affaire')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='N° facture / contrat')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='Mots-clés')),
                ('sha256', models.CharField(blank=True, max_length=64, verbose_name='Empreinte courante')),
                ('checked_out_at', models.DateTimeField(blank=True, null=True, verbose_name='Verrouillé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_documents', to=settings.AUTH_USER_MODEL, verbose_name='Verrouillé par')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documenttype', verbose_name='Type de document')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(verbose_name='Numéro de version')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Fichier')),
                ('sha256', models.CharField(max_length=64, verbose_name='Empreinte SHA-256 (RF-67)')),
                ('size', models.PositiveBigIntegerField(verbose_name='Taille (octets)')),
                ('original_filename', models.CharField(max_length=255, verbose_name="Nom d'origine")),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note de version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'verbose_name': 'Version',
                'ordering': ['document', '-number'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.version', verbose_name='Version courante'),
        ),
        migrations.AddConstraint(
            model_name='dossier',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='uniq_dossier_sibling_name'),
        ),
    ]
