# Generated by Django 5.2.17 on 2026-08-10 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('read', 'Lecture'), ('write', 'Écriture'), ('deny', 'Refus explicite')], default='read', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acl', to='documents.document')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_acls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Droit document (ACL)',
                'verbose_name_plural': 'Droits document (ACL)',
                'constraints': [models.UniqueConstraint(fields=('document', 'user'), name='uniq_document_access')],
            },
        ),
        migrations.CreateModel(
            name='DossierAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('read', 'Lecture'), ('write', 'Écriture'), ('deny', 'Refus explicite')], default='read', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acl', to='documents.dossier')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_acls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Droit dossier (ACL)',
                'verbose_name_plural': 'Droits dossier (ACL)',
                'constraints': [models.UniqueConstraint(fields=('dossier', 'user'), name='uniq_dossier_access')],
            },
        ),
    ]
