# Generated by Django 5.2.17 on 2026-08-10 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentaccess_dossieraccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('download', 'Téléchargement / export'), ('print', 'Impression'), ('acl_grant', 'Droit accordé'), ('acl_revoke', 'Droit retiré')], max_length=20, verbose_name='Action')),
                ('object_type', models.CharField(max_length=50, verbose_name="Type d'objet")),
                ('object_id', models.CharField(max_length=36, verbose_name="Identifiant de l'objet")),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='Détail')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Entrée d'audit",
                'verbose_name_plural': "Piste d'audit",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='documents_a_object__a6ebff_idx'), models.Index(fields=['user', '-created_at'], name='documents_a_user_id_85938c_idx')],
            },
        ),
    ]
