# Generated by Django 5.2.17 on 2026-08-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archivé le'),
        ),
        migrations.AddField(
            model_name='document',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rejeté le'),
        ),
        migrations.AddField(
            model_name='document',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Motif de rejet (RF-39)'),
        ),
        migrations.AddField(
            model_name='document',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Soumis le (circuit de validation)'),
        ),
    ]
