# Generated by Django 5.2.17 on 2026-08-10 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_archived_at_document_rejected_at_and_more'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='circuit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_types', to='workflow.circuit', verbose_name='Circuit de validation (RF-29 à 31)'),
        ),
    ]
