# Generated by Django 5.2.17 on 2026-09-22 23:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting_kernel', '0001_initial'),
        ('referentiels', '0002_currency_unitofmeasure_account_analyticaxis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleGestionSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10, unique=True, verbose_name='Type')),
                ('prefix', models.CharField(max_length=10, verbose_name='Préfixe')),
                ('padding', models.PositiveSmallIntegerField(default=5, verbose_name='Zéro-padding')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Prochain numéro')),
            ],
            options={
                'verbose_name': 'Séquence Contrôle de gestion',
                'verbose_name_plural': 'Séquences Contrôle de gestion',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=250, verbose_name='Intitulé du budget')),
                ('type_budget', models.CharField(choices=[('charge', 'Budget de charges'), ('produit', 'Budget de produits')], db_index=True, max_length=10, verbose_name='Type')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Montant (FCFA)')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('approuve', 'Approuvé'), ('cloture', 'Clôturé')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analytic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='referentiels.analyticaccount', verbose_name="Valeur d'axe (affaire / chantier / CC)")),
                ('axis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='referentiels.analyticaxis', verbose_name='Axe analytique')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_cg', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='accounting_kernel.fiscalyear', verbose_name='Exercice')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['-fiscal_year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClotureGestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('date_cloture', models.DateField(blank=True, null=True, verbose_name='Date de clôture')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('realisee', 'Réalisée')], default='en_attente', max_length=12, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures_cg', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clotures_gestion', to='accounting_kernel.period', verbose_name='Période comptable')),
            ],
            options={
                'verbose_name': 'Clôture de gestion',
                'verbose_name_plural': 'Clôtures de gestion',
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLigne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Montant (FCFA)')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='controle_gestion.budget', verbose_name='Budget')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lignes', to='accounting_kernel.period', verbose_name='Période comptable')),
            ],
            options={
                'verbose_name': 'Ligne de budget',
                'verbose_name_plural': 'Lignes de budget',
                'ordering': ['budget', 'period'],
                'constraints': [models.UniqueConstraint(fields=('budget', 'period'), name='uniq_budget_ligne_period')],
            },
        ),
        migrations.CreateModel(
            name='BudgetRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='N° de révision (1-4)')),
                ('date_revision', models.DateField(verbose_name='Date de révision')),
                ('ancien_montant', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Montant avant révision')),
                ('nouveau_montant', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Montant après révision')),
                ('commentaire', models.CharField(blank=True, max_length=250, verbose_name='Commentaire')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('appliquee', 'Appliquée'), ('annulee', 'Annulée')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='controle_gestion.budget', verbose_name='Budget')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions_cg', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
            ],
            options={
                'verbose_name': 'Révision budgétaire',
                'verbose_name_plural': 'Révisions budgétaires',
                'ordering': ['budget', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('budget', 'numero'), name='uniq_budget_revision_numero')],
            },
        ),
    ]
