# Generated by Django 5.2.17 on 2026-09-21 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiels', '0002_currency_unitofmeasure_account_analyticaxis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True, verbose_name='Exercice')),
                ('start_date', models.DateField(verbose_name='Début')),
                ('end_date', models.DateField(verbose_name='Fin')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Clôturé')], default='open', max_length=8, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Exercice',
                'verbose_name_plural': 'Exercices',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=120, verbose_name='Libellé')),
                ('journal_type', models.CharField(choices=[('vente', 'Ventes'), ('achat', 'Achats'), ('tresorerie', 'Trésorerie'), ('paie', 'Paie'), ('stock', 'Stock'), ('od', 'Opérations diverses')], db_index=True, max_length=12, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journaux',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccountMove',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, verbose_name='Date comptable')),
                ('number', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Numéro')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='Référence')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='Libellé')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('posted', 'Comptabilisée'), ('reversed', 'Extournée')], db_index=True, default='draft', max_length=10, verbose_name='Statut')),
                ('source', models.CharField(blank=True, help_text='Ex. M10, M9, M5.', max_length=20, verbose_name='Module source')),
                ('source_ref', models.CharField(blank=True, max_length=60, verbose_name='Réf. source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_moves', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverses', to='accounting_kernel.accountmove', verbose_name='Extournée par')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='accounting_kernel.journal', verbose_name='Journal')),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'verbose_name_plural': 'Écritures comptables',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountMoveLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='Libellé')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Débit')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Crédit')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='move_lines', to='referentiels.account', verbose_name='Compte')),
                ('analytic_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_lines', to='referentiels.analyticaccount', verbose_name='Axe analytique')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting_kernel.accountmove', verbose_name='Écriture')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_lines', to='referentiels.partner', verbose_name='Tiers')),
            ],
            options={
                'verbose_name': "Ligne d'écriture",
                'verbose_name_plural': "Lignes d'écriture",
                'ordering': ['move', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='N° (1-12)')),
                ('start_date', models.DateField(verbose_name='Début')),
                ('end_date', models.DateField(verbose_name='Fin')),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('closed', 'Clôturée')], default='open', max_length=8, verbose_name='Statut')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='accounting_kernel.fiscalyear', verbose_name='Exercice')),
            ],
            options={
                'verbose_name': 'Période',
                'verbose_name_plural': 'Périodes',
                'ordering': ['fiscal_year', 'number'],
            },
        ),
        migrations.AddField(
            model_name='accountmove',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='accounting_kernel.period', verbose_name='Période'),
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10, verbose_name='Préfixe')),
                ('padding', models.PositiveSmallIntegerField(default=5, verbose_name='Zéro-padding')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Prochain numéro')),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='accounting_kernel.journal', verbose_name='Journal')),
            ],
            options={
                'verbose_name': 'Séquence',
                'verbose_name_plural': 'Séquences',
            },
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('fiscal_year', 'number'), name='uniq_period_year_number'),
        ),
        migrations.AddConstraint(
            model_name='accountmove',
            constraint=models.UniqueConstraint(fields=('journal', 'number'), name='uniq_move_journal_number'),
        ),
    ]
