# Generated by Django 5.2.17 on 2026-09-22 15:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0001_initial'),
        ('operations', '0001_initial'),
        ('referentiels', '0002_currency_unitofmeasure_account_analyticaxis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogistiqueSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10, unique=True, verbose_name='Type')),
                ('prefix', models.CharField(max_length=10, verbose_name='Préfixe')),
                ('padding', models.PositiveSmallIntegerField(default=5, verbose_name='Zéro-padding')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Prochain numéro')),
            ],
            options={
                'verbose_name': 'Séquence Logistique',
                'verbose_name_plural': 'Séquences Logistique',
            },
        ),
        migrations.CreateModel(
            name='DemandeMobilisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=200, verbose_name='Objet du besoin')),
                ('departement', models.CharField(blank=True, max_length=120, verbose_name='Département demandeur')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Début souhaité')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Fin souhaitée')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / spécifications')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('traitee', 'Traitée'), ('annulee', 'Annulée')], default='brouillon', max_length=12, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_logistique', to='commercial.affaire', verbose_name='Affaire')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistique_created_demandes', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('ordre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_logistique', to='operations.ordrefabrication', verbose_name='Ordre de fabrication')),
            ],
            options={
                'verbose_name': 'Demande de mobilisation',
                'verbose_name_plural': 'Demandes de mobilisation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipementParc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=200, verbose_name='Désignation')),
                ('registration', models.CharField(blank=True, max_length=40, verbose_name='Immatriculation / n° série')),
                ('categorie', models.CharField(choices=[('engin', 'Engin de chantier'), ('levage', 'Matériel de levage'), ('transport', 'Transport / véhicule'), ('atelier', "Matériel d'atelier"), ('materiel', 'Matériel divers')], default='engin', max_length=12, verbose_name='Catégorie')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('affecte', 'Affecté'), ('en_location', 'En location (GR)'), ('hors_service', 'Hors service'), ('maintenance', 'En maintenance')], default='disponible', max_length=14, verbose_name='Statut')),
                ('compteur_type', models.CharField(choices=[('heures', 'Heures moteur'), ('km', 'Kilomètres'), ('forfait', 'Forfait (sans compteur)')], default='heures', max_length=7, verbose_name='Type de compteur')),
                ('compteur_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valeur compteur')),
                ('site', models.CharField(blank=True, max_length=120, verbose_name='Site / dépôt')),
                ('is_global_rental', models.BooleanField(default=False, verbose_name='GLOBAL RENTAL')),
                ('signe_618', models.BooleanField(default=False, help_text='Coût/Gain GR isolé au compte 618 (SYSCOHADA).', verbose_name='Refacturation compte 618')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements_parc', to='referentiels.partner', verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Équipement du parc',
                'verbose_name_plural': 'Équipements du parc',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AffectationParc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('date_debut', models.DateField(verbose_name='Début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='active', max_length=12, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_logistique', to='commercial.affaire', verbose_name='Affaire')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistique_created_affectations', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('ordre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_logistique', to='operations.ordrefabrication', verbose_name='Ordre de fabrication')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistique_affectations', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations', to='logistique.demandemobilisation', verbose_name='Demande liée')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='logistique.equipementparc', verbose_name='Équipement')),
            ],
            options={
                'verbose_name': 'Affectation de parc',
                'verbose_name_plural': 'Affectations de parc',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationGR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('reference_bc', models.CharField(blank=True, max_length=40, verbose_name='BC (bon de commande)')),
                ('reference_gr', models.CharField(blank=True, max_length=40, verbose_name='GR (gréement)')),
                ('reference_bl', models.CharField(blank=True, max_length=40, verbose_name='BL (livraison)')),
                ('reference_retour', models.CharField(blank=True, max_length=40, verbose_name='Retour GR')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Début location')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Fin location')),
                ('periodicite', models.CharField(choices=[('heure', "À l'heure"), ('jour', 'À la journée'), ('mois', 'Au mois'), ('forfait', 'Forfait')], default='mois', max_length=7, verbose_name='Périodicité')),
                ('tarif', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Tarif unitaire')),
                ('montant_estime', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant estimé')),
                ('lecture_initiale', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Compteur départ')),
                ('lecture_finale', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Compteur retour')),
                ('imputation_618', models.BooleanField(default=True, verbose_name='Refacturation compte 618')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('active', 'Active'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='brouillon', max_length=12, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations_gr', to='commercial.affaire', verbose_name='Affaire')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistique_created_locations', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('devise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations_gr', to='referentiels.currency', verbose_name='Devise')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='logistique.equipementparc', verbose_name='Équipement')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations_gr', to='referentiels.partner', verbose_name='Partenaire GR')),
            ],
            options={
                'verbose_name': 'Prestation GLOBAL RENTAL',
                'verbose_name_plural': 'Prestations GLOBAL RENTAL',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LectureCompteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('date', models.DateField(verbose_name='Date du relevé')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valeur compteur')),
                ('type_lecture', models.CharField(choices=[('initiale', 'Initiale'), ('periodique', 'Périodique'), ('finale', 'Finale')], default='periodique', max_length=10, verbose_name='Type')),
                ('source', models.CharField(choices=[('saisie', 'Saisie ETSL'), ('gr', 'Reçu GLOBAL RENTAL')], default='saisie', max_length=6, verbose_name='Source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('releve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistique_lectures', to=settings.AUTH_USER_MODEL, verbose_name='Relevé par')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='logistique.locationgr', verbose_name='Prestation GR')),
            ],
            options={
                'verbose_name': 'Lecture de compteur',
                'verbose_name_plural': 'Lectures de compteur',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='demandemobilisation',
            index=models.Index(fields=['statut', 'date_debut'], name='logistique__statut_1b5856_idx'),
        ),
        migrations.AddIndex(
            model_name='equipementparc',
            index=models.Index(fields=['statut', 'categorie'], name='logistique__statut_969644_idx'),
        ),
        migrations.AddIndex(
            model_name='affectationparc',
            index=models.Index(fields=['statut', 'equipement'], name='logistique__statut_6a9ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='locationgr',
            index=models.Index(fields=['statut', 'partenaire'], name='logistique__statut_e3d005_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturecompteur',
            index=models.Index(fields=['location', 'date'], name='logistique__locatio_6dd309_idx'),
        ),
    ]
