# Generated by Django 5.2.17 on 2026-08-10 18:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0004_document_archived_at_document_rejected_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=120, verbose_name='Libellé')),
                ('max_days', models.PositiveSmallIntegerField(help_text='RF-35', verbose_name='Délai max global (jours)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Circuit',
                'verbose_name_plural': 'Circuits',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CircuitStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Ordre')),
                ('name', models.CharField(max_length=120, verbose_name="Nom de l'étape")),
                ('actor_role', models.CharField(choices=[('admin', 'Administrateur'), ('direction', 'Direction'), ('chef_service', 'Chef de service'), ('comptable', 'Comptable'), ('rh', 'RH')], max_length=20, verbose_name='Rôle acteur')),
                ('max_days', models.PositiveSmallIntegerField(default=1, verbose_name='Délai max (jours)')),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.circuit')),
            ],
            options={
                'verbose_name': 'Étape de circuit',
                'verbose_name_plural': 'Étapes de circuit',
                'ordering': ['circuit', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('done', 'Terminée'), ('rejected', 'Rejeté'), ('delegated', 'Déléguée')], default='pending', max_length=20)),
                ('due_date', models.DateTimeField(verbose_name='Échéance (RF-35)')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Assigné par')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='workflow.circuit')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='documents.document')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='workflow.circuitstep')),
            ],
            options={
                'verbose_name': 'Tâche de workflow',
                'verbose_name_plural': 'Tâches de workflow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Texte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workflow.task')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='circuitstep',
            constraint=models.UniqueConstraint(fields=('circuit', 'order'), name='uniq_circuit_step_order'),
        ),
    ]
