# Generated by Django 5.2.17 on 2026-09-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur (technique)'), ('pdg', 'PDG'), ('dga', 'DGA'), ('secretaire_general', 'Secrétariat Général'), ('directeur_projets', 'Directeur Projets'), ('directeur_operations', 'Directeur Opérations'), ('rh', 'Ressources Humaines'), ('finance', 'Finance / Comptabilité / Contrôle de gestion'), ('qaqc', 'QA/QC'), ('hse', 'HSE'), ('logistique', 'Logistique & Magasin'), ('maintenance', 'Maintenance'), ('chef_atelier', "Chef d'atelier / chantier"), ('direction', 'Direction (hérité)'), ('chef_service', 'Chef de service (hérité)'), ('comptable', 'Comptable (hérité)')], default='admin', max_length=20, verbose_name='Rôle'),
        ),
    ]
