# Generated by Django 5.2.17 on 2026-09-21 16:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(db_index=True, max_length=60, verbose_name='Sujet')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Données')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('delivered', 'Livrée'), ('failed', 'Échouée (abandonnée)')], db_index=True, default='pending', max_length=10, verbose_name='Statut')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, verbose_name='Tentatives')),
                ('error_message', models.TextField(blank=True, verbose_name='Dernière erreur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Livrée le')),
            ],
            options={
                'verbose_name': 'Événement outbox',
                'verbose_name_plural': 'Événements outbox',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='outbox_outb_status_ab1c80_idx')],
            },
        ),
    ]
