# Generated by Django 5.2.17 on 2026-09-23 00:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0001_initial'),
        ('documents', '0006_document_extracted_text_document_search_vector_and_more'),
        ('referentiels', '0002_currency_unitofmeasure_account_analyticaxis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JuridiqueSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10, unique=True, verbose_name='Type')),
                ('prefix', models.CharField(max_length=10, verbose_name='Préfixe')),
                ('padding', models.PositiveSmallIntegerField(default=5, verbose_name='Zéro-padding')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Prochain numéro')),
            ],
            options={
                'verbose_name': 'Séquence Juridique',
                'verbose_name_plural': 'Séquences Juridique',
            },
        ),
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('type', models.CharField(choices=[('rc_pro', 'Responsabilité civile professionnelle'), ('tous_risques', 'Tous risques chantier'), ('flotte', 'Flotte automobile'), ('engins', 'Engins & matériel'), ('bris_machine', 'Bris de machine'), ('vie_groupe', 'Prévoyance / vie de groupe'), ('multirisque', 'Multirisque immeuble'), ('autre', 'Autre')], max_length=16, verbose_name='Type')),
                ('numero_police', models.CharField(max_length=120, verbose_name='N° police')),
                ('prime_annuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Prime annuelle (FCFA)')),
                ('date_debut', models.DateField(verbose_name="Date d'effet")),
                ('date_echeance', models.DateField(verbose_name='Échéance')),
                ('objets_couverts', models.CharField(blank=True, max_length=250, verbose_name='Objets couverts')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('a_renouveler', 'À renouveler (échéance proche)'), ('expiree', 'Expirée'), ('resiliee', 'Résiliée')], default='active', max_length=14, verbose_name='Statut')),
                ('nb_sinistres', models.PositiveSmallIntegerField(default=0, verbose_name='Nombre de sinistres')),
                ('sinistres', models.JSONField(blank=True, default=list, verbose_name='Sinistres déclarés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assureur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assurances', to='referentiels.partner', verbose_name='Assureur')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assurances_juridique', to='documents.document', verbose_name='Police (GED)')),
            ],
            options={
                'verbose_name': 'Assurance',
                'verbose_name_plural': 'Assurances',
                'ordering': ['-date_echeance'],
            },
        ),
        migrations.CreateModel(
            name='Contentieux',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('nature', models.CharField(choices=[('commercial', 'Commercial'), ('social', "Social / prud'homal"), ('fiscal', 'Fiscal'), ('assurances', 'Assurances'), ('fournisseur', 'Fournisseur / sous-traitant'), ('client', 'Client'), ('autre', 'Autre')], max_length=14, verbose_name='Nature')),
                ('objet', models.CharField(max_length=250, verbose_name='Objet du litige')),
                ('partie_adverse', models.CharField(max_length=200, verbose_name='Partie adverse')),
                ('conseil_ext', models.CharField(blank=True, max_length=200, verbose_name='Conseil / avocat')),
                ('montant_en_jeu', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Montant en jeu (FCFA)')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='Référence')),
                ('date_ouverture', models.DateField(default=django.utils.timezone.localdate, verbose_name="Date d'ouverture")),
                ('phase', models.CharField(choices=[('pre_contentieux', 'Pré-contentieux / mise en demeure'), ('tribunal', 'Instance (tribunal)'), ('arbitrage', 'Arbitrage'), ('appel', 'Appel')], default='pre_contentieux', max_length=20, verbose_name='Phase')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_instruction', 'En instruction'), ('gagne', 'Gagné'), ('perdu', 'Perdu'), ('transaction', 'Transaction / accord'), ('cloture', 'Clôturé')], default='ouvert', max_length=20, verbose_name='Statut')),
                ('decision', models.TextField(blank=True, verbose_name='Décision / issue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contentieux_juridique', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contentieux_juridique', to='documents.document', verbose_name='Dossier contentieux (GED)')),
            ],
            options={
                'verbose_name': 'Contentieux',
                'verbose_name_plural': 'Contentieux',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('type', models.CharField(choices=[('marche_travaux', 'Marché de travaux'), ('maintenance', 'Contrat de maintenance'), ('prestation', 'Prestation de services'), ('bail', 'Bail / loyer'), ('partenariat', 'Partenariat / coopération'), ('avenant', 'Avenant'), ('autre', 'Autre')], max_length=16, verbose_name='Type')),
                ('titre', models.CharField(max_length=250, verbose_name='Intitulé')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Montant (FCFA)')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('renouvelable', models.BooleanField(default=False, verbose_name='Renouvelable')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_signature', 'En signature'), ('signe', 'Signé (en cours de validité)'), ('cloture', 'Clôturé'), ('resilie', 'Résilié')], default='brouillon', max_length=14, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions', to='commercial.affaire', verbose_name='Affaire M1')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions_juridique', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions_juridique', to='documents.document', verbose_name='Convention signée (GED)')),
                ('partenaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions', to='referentiels.partner', verbose_name='Partenaire / cocontractant')),
            ],
            options={
                'verbose_name': 'Convention / contrat',
                'verbose_name_plural': 'Conventions / contrats',
                'ordering': ['-date_fin'],
            },
        ),
        migrations.CreateModel(
            name='Caution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('type', models.CharField(choices=[('bon_soumission', 'Bon de soumission'), ('bonne_execution', 'Bonne exécution'), ('avance', "Remboursement d'avance"), ('retenue', 'Retenue de garantie')], max_length=18, verbose_name='Type')),
                ('beneficiaire', models.CharField(max_length=200, verbose_name="Bénéficiaire / maître d'ouvrage")),
                ('objet', models.CharField(max_length=250, verbose_name='Objet de la garantie')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Montant (FCFA)')),
                ('numero_instrument', models.CharField(blank=True, max_length=120, verbose_name='N° instrument bancaire')),
                ('date_emission', models.DateField(verbose_name="Date d'émission")),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('statut', models.CharField(choices=[('en_cours', 'En cours de validité'), ('levee', 'Levée / restituée'), ('appelee', 'Appelée'), ('expiree', 'Expirée')], default='en_cours', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cautions_juridique', to='documents.document', verbose_name='Garantie (GED)')),
                ('emetteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cautions_emises', to='referentiels.partner', verbose_name='Émetteur (banque / assureur)')),
                ('convention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cautions', to='juridique.convention', verbose_name='Convention liée')),
            ],
            options={
                'verbose_name': 'Caution / garantie',
                'verbose_name_plural': 'Cautions / garanties',
                'ordering': ['-date_echeance'],
            },
        ),
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('sens', models.CharField(choices=[('entrant', 'Entrant'), ('sortant', 'Sortant')], max_length=8, verbose_name='Sens')),
                ('type', models.CharField(choices=[('lettre', 'Lettre'), ('email', 'E-mail'), ('note', 'Note interne'), ('convocation', 'Convocation'), ('proces', 'Procès-verbal'), ('autre', 'Autre')], max_length=12, verbose_name='Type')),
                ('objet', models.CharField(max_length=250, verbose_name='Objet')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='Référence')),
                ('expediteur', models.CharField(blank=True, max_length=200, verbose_name='Expéditeur')),
                ('destinataire', models.CharField(blank=True, max_length=200, verbose_name='Destinataire')),
                ('date_courrier', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date du courrier')),
                ('date_reception', models.DateField(blank=True, null=True, verbose_name='Date de réception (entrant)')),
                ('statut', models.CharField(choices=[('recu', 'Reçu'), ('enregistre', "Enregistré (bureau d'ordre)"), ('classe', 'Classé & indexé'), ('archive', 'Archivé & conservé')], default='recu', max_length=12, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Annotations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_juridique', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers', to='documents.document', verbose_name='Document classé (GED)')),
                ('tiers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers', to='referentiels.partner', verbose_name='Correspondant')),
            ],
            options={
                'verbose_name': 'Courrier',
                'verbose_name_plural': "Courriers (bureau d'ordre)",
                'ordering': ['-date_courrier', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DossierGlobalRental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('reference_contrat', models.CharField(blank=True, max_length=120, verbose_name='Référence contrat / convention')),
                ('objet', models.CharField(max_length=250, verbose_name='Objet de la prestation')),
                ('montant_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Montant estimé (FCFA)')),
                ('signe_618', models.BooleanField(default=False, verbose_name='Refacturation imputée au compte 618000')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('ouvert', 'Ouvert'), ('cloture', 'Clôturé')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('references_documents', models.JSONField(blank=True, default=list, verbose_name='Références BC / GR / BL / retour GR')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_gr', to='commercial.affaire', verbose_name='Affaire M1')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_gr', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('partenaire_gr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers_gr', to='referentiels.partner', verbose_name='Partenaire GLOBAL RENTAL')),
            ],
            options={
                'verbose_name': 'Dossier intra-groupe GLOBAL RENTAL',
                'verbose_name_plural': 'Dossiers intra-groupe GLOBAL RENTAL',
                'ordering': ['-date_fin'],
            },
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('type', models.CharField(choices=[('comite_direction', 'Comité de direction'), ('revue_chantier', 'Réunion de chantier'), ('revue_atelier', "Réunion d'atelier"), ('revue_qualite', 'Revue qualité'), ('securite', 'Réunion sécurité (HSE)'), ('retroplanning', 'Revue planning / rétroplanning'), ('autre', 'Autre')], max_length=20, verbose_name='Type')),
                ('objet', models.CharField(max_length=250, verbose_name='Objet / ordre du jour')),
                ('date_reunion', models.DateTimeField(verbose_name='Date')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('tenue', 'Tenue'), ('cloturee', 'Clôturée')], default='planifiee', max_length=10, verbose_name='Statut')),
                ('decisions', models.JSONField(blank=True, default=list, verbose_name='Décisions & actions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunions_animees', to=settings.AUTH_USER_MODEL, verbose_name='Animateur')),
                ('compte_rendu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunions_juridique', to='documents.document', verbose_name='Compte rendu (GED)')),
                ('participants', models.ManyToManyField(blank=True, related_name='reunions_participations', to=settings.AUTH_USER_MODEL, verbose_name='Participants')),
            ],
            options={
                'verbose_name': 'Réunion',
                'verbose_name_plural': 'Réunions',
                'ordering': ['-date_reunion'],
            },
        ),
    ]
